### PR TITLE
Mavenize, project cleanup

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by RoboTricker** [comment]
wow, thanks for that cleanup, I didn't have that much experience with maven and such a dependency management system.

**Comment by sgdc3** [comment]
You're welcome ;)

**Comment by RoboTricker** [comment]
do you know a good tutorial about maven?

**Comment by sgdc3** [comment]
The issue with maven is the documentation, people keeps using it in the wrong way. I've seen many "pro" developers mave huge mistakes. The best way to learn how to use it correctly is to look at the setup of some famous open source projects.

**Comment by RoboTricker** [comment]
ok I will do that, thanks :)

**Comment by RoboTricker** [comment]
Can I compile/build the final jar file with maven? Until now I exported the jar with eclipse export wizard.

**Comment by sgdc3** [comment]
you should import the project again as maven project

**Pull request merged**
