### PR TITLE
Implement NBT filtering

### PR DESCRIPTION
**Pull request by sgdc3**
Review is needed

### CODE REVIEW

**Review by RoboTricker — COMMENTED** [review]
not bad but do you think the users will understand what it means?

**Comment by sgdc3** [comment]
Many forge mods have such feature, i think many players are going to use it ;)

**Comment by sgdc3** [comment]
@keke142 If you want we can also add the messages to the configuration

**Comment by RoboTricker** [comment]
I'm currently doing that, I will commit it right away :)

**Pull request merged**
