### PR TITLE
Add configuration support and fixing critical CPU usage

### PR DESCRIPTION
**Pull request by jdkeke142**

### CODE REVIEW

**Comment by RoboTricker** [comment]
Why do you think a Thread.sleep will fix the CPU issue?

**Comment by jdkeke142** [comment]
Without  sleep, the  loop use all the computing resources that is available. In any case it seems to work, on my machine the use of the CPU is now much less. Before the use of the CPU was 50% to 100%. I leave you tried.

**Comment by sgdc3** [comment]
He is right, a loop will keep the cpu time usage very high, a sleeping thread is handled by the jvm and the OS in order to minimize resource usage

**Comment by sgdc3** [comment]
I think that config should't be used before plugin initialization. Also, i think "locale" or "messages" would be a better name.

**Pull request merged**
