### PR TITLE
Implement damageable pipes (explosion) + fix JNBT dependency

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Review by RoboTricker — CHANGES_REQUESTED** [review]
there are too many servers running Java 1.7
Could you downgrade it to 1.7 please?

**Comment by sgdc3** [comment]
Ok, are you sure? xD https://bstats.org/global/bukkit
600/30000 servers use java 1.7

**Comment by sgdc3** [comment]
whoops, wrong button xD

**Comment by RoboTricker** [comment]
Yeah, some months ago I updated the plugin to 1.8 by mistake xD and then there had come several reviews that the plugin wouldn't work anymore

**Comment by sgdc3** [comment]
some months ago ;)

**Review by RoboTricker — APPROVED** [review]

**Comment by sgdc3** [comment]
@RoboTricker any news? ;)

**Comment by sgdc3** [comment]
@RoboTricker bump

**Comment by RoboTricker** [comment]
The thing is in my next commit on the branch model-system I'll have changed a lot inside the TransportPipes class (code cleanup etc). Therefore let's first see, what the merging issues will be.

**Comment by sgdc3** [comment]
Pls merge xD
@RoboTricker

**Pull request merged**
